### ISSUE TITLE
No way to apply some analysis more than once

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/camshaft#268]
STR:

You have
* DATASET A : columns `(cartodb_id, the_geom, the_geom_webmercator, kpi1, kpi2)`
* DATASET B and DATASET C: with the same streucture: columns `(cartodb_id, the_geom, the_geom_webmercator, kpi3, a_id)`

You want to join A with B and then with C, so you get a DATASET Z with columns 

(cartodb_id, the_geom, the_geom_webmercator, kpi1, kpi2, **B_kpi3**, **C_kpi3**)

So you perform the first **left join** (left.cartodb_id = right.a_id) and you get

(cartodb_id, the_geom, the_geom_webmercator, kpi1, kpi2, **right_kpi3**)

Now you want to join the third dataset the same way:

YOU GET AN ERROR BECAUSE THERE'S ALREADY A COLUMN CALLED `RIGHT_KPI3`

so you can't perform the join again

cc @dgaubert

**Comment by ethervoid** [comment]
Doing some tests for another issue, I've got into this.

A quick test is to make the source of a trade-area analysis another trade-area analysis. Doing this you're going to get the following error message:

```
Uncaught AssertionError: error: column "center" specified more than once
      + expected - actual

      -false
      +true

      at test/integration/nodes.js:393:24
      at analysis$finish (lib/analysis.js:120:24)
      at node_modules/async/lib/async.js:52:16
      at node_modules/async/lib/async.js:696:30
      at node_modules/async/lib/async.js:167:37
      at node_modules/async/lib/async.js:1209:30
      at lib/workflow/factory.js:108:36
      at lib/service/database.js:146:24
      at lib/service/database.js:112:16
      at lib/postgresql/query-runner.js:37:16
      at Function.<anonymous> (node_modules/cartodb-psql/lib/psql.js:496:17)
      at next [as callback] (node_modules/cartodb-psql/node_modules/step/lib/step.js:51:23)
      at Query.handleError (node_modules/cartodb-psql/node_modules/pg/lib/query.js:129:17)
      at null.<anonymous> (node_modules/cartodb-psql/node_modules/pg/lib/client.js:184:26)
      at Socket.<anonymous> (node_modules/cartodb-psql/node_modules/pg/lib/connection.js:123:12)
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)
```

**Comment by AbelVM** [comment]
This issue happens with each and every analysis that add any extra column to the original table.
