### ISSUE TITLE
Uncaught exception in some Batch API errors

### ISSUE THREAD

**Issue by rafatower** [CartoDB/camshaft#380]
```
Uncaught exception: TypeError: response.match is not a function
    at batchErrorMessage (/home/rtorre/src/Windshaft-cartodb/node_modules/camshaft/lib/postgresql/batch-client.js:25:49)
    at Request._callback (/home/rtorre/src/Windshaft-cartodb/node_modules/camshaft/lib/postgresql/batch-client.js:54:39)
    at Request.self.callback (/home/rtorre/src/Windshaft-cartodb/node_modules/camshaft/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/rtorre/src/Windshaft-cartodb/node_modules/camshaft/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/rtorre/src/Windshaft-cartodb/node_modules/camshaft/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)
```

Related to https://github.com/CartoDB/camshaft/pull/378

**Comment by rafatower** [comment]
How I reproduced the issue locally and in prod:
- Import some dataset. eg: `brooklyn_poverty`
- Replace the `SELECT *` with an equivalent long query (a comment of 16kb):
```javascript
// file longquery.js

var query = 'SELECT /* ';
for(var i=0; i < (16*1024); ++i) {
    query += 'x';
}
query += '*/ * FROM brooklyn_poverty'

var fs = require('fs');
fs.writeSync(1, query);
fs.fsyncSync(1);
```

```bash
node longquery.js > query.sql
```
- create a centroids and on top of it a buffer analysis.
